# -*- coding: utf-8 -*-
"""cvm_captura_informacoes_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17MpgR_uCmF4c-7YqTxuij7A3b3S_3y2M
"""


from requests_html import HTMLSession
import requests
from tqdm import tqdm
import os

def download_file(url, file_name):
    response = requests.get(url, stream=True)
    with open(file_name, "wb") as handle:
        for data in tqdm(response.iter_content()):
            handle.write(data)
    handle.close()

    
def create_download_folder():
    # Create directory
    dirName = os.path.join('downloads')
 
    try:
        # Create target Directory
        os.mkdir(dirName)
        print("Directory", dirName, "Created ")
    except Exception:
        print("Directory", dirName, "already exists")


def get_list_files_cvm_site(url):
    session = HTMLSession()
    r = session.get(url)
    
    if r.status_code != 200:
        print('Erro ao acessar site da CVM')
        return False

    links = []
    for link in r.html.absolute_links:
        if not link.endswith('.csv'):
            continue
        links.append(link)

    return links


def download_files(links):
    for link in links:
        if not link.endswith('.csv'):
            continue
        
        file_name = link.split('/')[-1]
        file_path = os.path.join('downloads', file_name)

        if os.path.exists(file_path):
            print('Arquivo já baixado, indo para o próximo', file_path)
            continue

        print('Fazendo download do arquivo', link)
        download_file(link, file_path)


# main
urls = [
    'http://dados.cvm.gov.br/dados/FI/DOC/PERFIL_MENSAL/DADOS/',
    'http://dados.cvm.gov.br/dados/FI/DOC/EXTRATO/DADOS/',
    'http://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/',
    # dados de intermediários financeiros
    'http://dados.cvm.gov.br/dados/INTERMEDIARIO/CAD/DADOS/',
    # dados das companhias abertas
    'http://dados.cvm.gov.br/dados/CIA_ABERTA/CAD/DADOS/',
    # doctos eventuais, como ata de AGO, regulamentos
    'http://dados.cvm.gov.br/dados/FI/DOC/EVENTUAL/DADOS/',
    # informações cadastrais de fundos estruturados
    'http://dados.cvm.gov.br/dados/FIE/CAD/DADOS/',
    # dados cadastrais diários de fundos 555
    'http://dados.cvm.gov.br/dados/FI/CAD/DADOS/',
]

create_download_folder()

for url in urls:
    links = get_list_files_cvm_site(url)
    download_files(links)
